<main class="container py-5">
    <h1>
        Créer un utilisateur
    </h1>
    <form class="mt-5" action="../logic/create-user.php" method="POST">
        <fieldset>
            <label for="email" class="form-label">Email</label>
            <input type="email" id="email" name="email" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" id="password" name="password" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="first_name" class="form-label">Prénom</label>
            <input type="text" id="first_name" name="first_name" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="last_name" class="form-label">Nom</label>
            <input type="text" id="last_name" name="last_name" class="form-control" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
    </form>
</main>